### ISSUE TITLE
Missing Options page

### ISSUE THREAD

**Issue by theRescuer** [fiatjaf/nos2x#1]
Hello,

I've installed the extension on
Firefox 96.0.2.
Windows 10 V. 21H2
It's not possible to get access to the "options" page. No link or button available
![immagine](https://user-images.githubusercontent.com/6945447/151002848-9081d879-51a4-4816-820b-0c42ea1a0707.png)

**Comment by fiatjaf** [comment]
Have you tried right-clicking the extension icon? (That works on Chromium, not sure about Firefox)

**Comment by theRescuer** [comment]
Hi,

Right clicking the extension icon brings you the menu for manging extensions (see screenshot 1. It's italian but understandable, I guess)
![immagine](https://user-images.githubusercontent.com/6945447/151114224-e71e1921-9629-4d10-8a69-a05f4108e52d.png)

From here I can only set up access grants to the extension 
![immagine](https://user-images.githubusercontent.com/6945447/151114821-11c11079-34ad-4868-8f8e-e2ff2fcee54a.png)

**Comment by fiatjaf** [comment]
Thank you for the detailed report.

Fixed on https://github.com/fiatjaf/nos2x/commit/3524838a411c8b1db43d476bd226075ac5ab5938, will be on the Firefox add-ons directory soon.
