### ISSUE TITLE
please provide firefox dev/install instructions

### ISSUE THREAD

**Issue by Giszmo** [fiatjaf/nos2x#10]
I did use `pnpm` to compile but that worked just fine for Chromium:

```
$ git checkout chromium
$ pnpm install
$ pnpm install readable-stream buffer
$ pnpm run build
```

For firefox:

```
$ git checkout firefox
$ pnpm install
$ pnpm install readable-stream buffer
$ pnpm run build
```

succeeded, too but I couldn't find how to load it in firefox.

**Comment by fiatjaf** [comment]
You must open the `about:debugging` page on Firefox.

**Comment by Giszmo** [comment]
Sorry, I fail to find how to load the extension from there. All I can find are things that expect an xpi or a zip file. Nothing allows me to load a folder and I assume I have to load the extension/ folder like with Chrome, right?

**Comment by fiatjaf** [comment]
https://developer.mozilla.org/en-US/docs/Mozilla/Add-ons/WebExtensions/Your_first_WebExtension

![2022-12-19-160213_791x268_scrot](https://user-images.githubusercontent.com/1653275/208500486-135d79af-aa02-4c31-847a-c339f673ab60.png)

**Comment by Giszmo** [comment]
Ok, that's ... weird. The "click any file" part was what I had not considered after having found the "Load Temporary Add-on.

I think this should be mentioned in the Readme.md as it was a considerate point of friction when I was about to get tinkering with this repo.

**Comment by fiatjaf** [comment]
Please open a pull request for that.

I find it very painful to maintain two versions of the same extension just because Chrome has decided to force Manifest v3, and because of that the Firefox version is abandoned.

**Comment by Giszmo** [comment]
#14
