### ISSUE TITLE
Error when trying to post: "Did not publish: TypeError: hexToBytes: expected string, got object"

### ISSUE THREAD

**Issue by kevinsmith** [fiatjaf/nos2x#12]
When using the extension to sign, I'm getting this error in Brave and Firefox (on macOS Ventura, fwiw) when trying to publish on https://nostr.rocks

> Did not publish: TypeError: hexToBytes: expected string, got object

I'm unable to do most anything else with the app either. Can't change username, follow others, etc. I don't necessarily get that exact error with other web-based nostr apps (like https://astral.ninja), I just get silent errors. But the effect is the same. Nothing works.

When I enter my private key into the app directly, then everything works.

**Comment by fiatjaf** [comment]
Do you get the same error on https://alphaama.com or https://metadata.nostr.com? I use these two regularly and it works fine on these two for me so I am thinking this might be a bug on Astral, but I don't know.

**Comment by kevinsmith** [comment]
I was able to use https://metadata.nostr.com/ to update my "about" with the extension, so that's good news. Since it's happening on both astral and rocks, maybe a bug in branle? I'll dig back in later today to see what I can find.

**Comment by ozoono** [comment]
I am having exactly the same problem in astral and rocks

**Comment by fiatjaf** [comment]
This is a problem in Astral and Rocks, please notify them.
