### ISSUE TITLE
Support for nsec1 type private keys

### ISSUE THREAD

**Issue by alinostr** [fiatjaf/nos2x#17]
Really love this minimal extension. Only problem that nsec1 private keys can not be saved. Button "save" is grayed out

**Comment by trader173** [comment]
still refusing nsec1 key.

**Comment by fiatjaf** [comment]
Works for me.

Firefox is not supported. Use nos2x-fox instead.

**Comment by trader173** [comment]
thanks boss.   all is working well now.

thanks for all the effort!

73 de ki4die
