### ISSUE TITLE
Interaction is a little confusing

### ISSUE THREAD

**Issue by amandafanny** [fiatjaf/nos2x#23]
There‘s two many save button.

<img width="1197" alt="image" src="https://user-images.githubusercontent.com/54808661/216745929-2a9f6d71-8b58-4678-a719-be865e607cb4.png">

<img width="784" alt="image" src="https://user-images.githubusercontent.com/54808661/216745823-97e0acda-0484-477d-8fe9-4eaefa3ee691.png">

**Comment by fiatjaf** [comment]
ahahah indeed.

**Comment by monlovesmango** [comment]
@fiatjaf would you like a save button for each section that appears after a user makes changes to a section or one universal save button for all options? or did you have something else in mind?

**Comment by fiatjaf** [comment]
I didn't have anything in mind. Actually I am very confused by this myself too, so I just click all the save buttons I can find every time I change something.
