### ISSUE TITLE
relays’s input‘s bug

### ISSUE THREAD

**Issue by amandafanny** [fiatjaf/nos2x#24]
when I click save, there's many input. And I can't remove it.
<img width="759" alt="image" src="https://user-images.githubusercontent.com/54808661/216746024-d28ea460-d6d4-40bc-9925-3ab75ae5e720.png">

<img width="765" alt="image" src="https://user-images.githubusercontent.com/54808661/216746130-95fc48ee-08ae-4b07-adbb-0a1dffbc920e.png">

**Comment by AsaiToshiya** [comment]
I think we can close this issue.
