### ISSUE TITLE
How do nostr: links work?

### ISSUE THREAD

**Issue by rolznz** [fiatjaf/nos2x#27]
I have the extension installed. Here is my config: 
![image](https://user-images.githubusercontent.com/33993199/217152353-a7d3e268-4347-4b78-8b77-cccabb8f12b2.png)

Here is an example link I tried to click on:
`<a href="nostr:note180tr4kp6xx4j7avvvtzzvumn07k9mppfgkasf929cn23mfwzstmqqjmrry">Nostr test</a>`

Nothing happens when I click on the link in the browser.

**Comment by fiatjaf** [comment]
Give me a webpage to try.

I just tried to click on the Nostr link that exists on https://fiatjaf.com/ and it worked.

**Comment by rolznz** [comment]
It works, thanks. It didn't work when I opened a local .html file with the link I added.
