### ISSUE TITLE
Error with Yarn

### ISSUE THREAD

**Issue by inpharmaticist** [fiatjaf/nos2x#30]
After cloning and CDing into nos2x, running `yarn` yields
```
00h00m00s 0/0: : ERROR: There are no scenarios; must have at least one.
```
Did I do something wrong? Running PopOS 22.04

**Comment by fiatjaf** [comment]
I have no idea. Never seen that before.

**Comment by inpharmaticist** [comment]
Answered [here](https://github.com/yarnpkg/yarn/issues/2821)
