### ISSUE TITLE
Firefox: Can't save private key

### ISSUE THREAD

**Issue by franciscojs12** [fiatjaf/nos2x#34]
Copying and pasting a private key is not triggering save. Save is triggered when clearing the private key field.
Firefox  v110.0.1 on MacOS v13.2.1 (Intel).

See video (private key is created solely for demo):
https://user-images.githubusercontent.com/31248802/223728669-79240de3-aa70-4e64-8457-6e2af6decbcc.mov

**Comment by fiatjaf** [comment]
The Firefox version is deprecated, use nos2x-fox.
