### ISSUE TITLE
[Feature Request] Store multiple nsec

### ISSUE THREAD

**Issue by antonioconselheiro** [fiatjaf/nos2x#56]
I am requesting a way to change the access credential without having to open the extension settings and change it manually, pasting my nsec from the secure place where I storaged it.

I have my personal account, my anonymous account (this), service accounts and organization accounts (for a brand or a company).

This make sense?

**Comment by fiatjaf** [comment]
Yes, it makes sense, but it's out of scope for this extension. I think there are other extensions out there that have support for multiple accounts.

**Comment by antonioconselheiro** [comment]
Not the extension scope, understood. Thank you for the reply.
