### ISSUE TITLE
Problem with webextension-polyfill

### ISSUE THREAD

**Issue by Anderson-Juhasc** [fiatjaf/nos2x#58]
I had to add the script webextension-polyfill to run, but now I have this problem when I try to save private key in Uint8Array format:

Uncaught (in promise) Error: Cannot serialize value to JSON at browser-polyfill.js:772:26

@fiatjaf  how did you solve this?

Thanks.

**Comment by Anderson-Juhasc** [comment]
Well, I'm not sure if it's a right way but worked, I tried this code to encode and decode the private key saved in local storage:

Encode:
`const myUint8Array = new Uint8Array([10, 20, 30]);
const encodedString = btoa(String.fromCharCode.apply(null, myUint8Array));
localStorage.setItem('myDataKey', encodedString);`

Decode:
`const encodedString = localStorage.getItem('myDataKey');
const decodedString = atob(encodedString);
const uint8Array = Uint8Array.from(decodedString.split('').map(c => c.charCodeAt(0)));
`

**Comment by fiatjaf** [comment]
Recent nostr-tools versions are return private keys in Uint8Array:

https://github.com/nbd-wtf/nostr-tools/pull/389/files
